apiVersion: v1
kind: ConfigMap

metadata:
  name: subscriber-config
  namespace: telecom

data:
  APP_NAME: "subscriber-service"

  SERVER_PORT: "7070"

  MONGO_URI: "mongodb://mongodb:27017"

  MONGO_DATABASE: "telecom"

  MONGO_COLLECTION: "subscribers"

  KAFKA_BROKER: "kafka:9092"

  KAFKA_TOPIC: "subscriber-events"