apiVersion: v1
kind: Service

metadata:
  name: subscriber-service
  namespace: telecom

spec:
  selector:
    app: subscriber-service

  type: NodePort

  ports:
    - port: 7070
      targetPort: 7070
      nodePort: 31727